# Generated by Django 5.2.8 on 2025-11-11 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FareRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("min_fare", models.PositiveIntegerField()),
                ("max_fare", models.PositiveIntegerField()),
                ("recommended_fare", models.PositiveIntegerField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fare_destinations",
                        to="core.stand",
                    ),
                ),
                (
                    "origin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fare_origins",
                        to="core.stand",
                    ),
                ),
            ],
            options={
                "unique_together": {("origin", "destination")},
            },
        ),
    ]
